{{- if .Values.users.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.users.secretName }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
type: Opaque
stringData:
  users_database.yml: |
    users:
{{- range $username, $user := .Values.users.entries }}
      {{ $username }}:
        displayname: {{ $user.displayname | quote }}
        password: {{ $user.password | quote }}
        email: {{ $user.email | quote }}
        {{- with $user.groups }}
        groups:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
